In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import seaborn as sns
import math

In [2]:
df = pd.read_csv('area_price.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3200       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
df['bedrooms'].fillna(math.floor(df['bedrooms'].median()), inplace=True)

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3200       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']].values,df['price'].values )

LinearRegression()

In [10]:
reg.intercept_

390780.8171745149

In [11]:
reg.coef_

array([   144.02700831, -34264.1966759 ,  -7120.84487535])

In [12]:
reg.predict([[3000,3,40]])

array([435235.45706371])

In [14]:
144.02700831*3000+ -34264.1966759*3 +  -7120.84487535*40 + 390780.8171745149

435235.4570628149

In [13]:
reg.predict([[2500,4,5]])

array([578187.32686981])